// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleStart.proto

#ifndef PROTOBUF_BattleStart_2eproto__INCLUDED
#define PROTOBUF_BattleStart_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BattleStart_2eproto();
void protobuf_AssignDesc_BattleStart_2eproto();
void protobuf_ShutdownFile_BattleStart_2eproto();

class BattleStartRequest;
class BattleStartResponse;

// ===================================================================

class BattleStartRequest : public ::google::protobuf::MessageLite {
 public:
  BattleStartRequest();
  virtual ~BattleStartRequest();
  
  BattleStartRequest(const BattleStartRequest& from);
  
  inline BattleStartRequest& operator=(const BattleStartRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BattleStartRequest& default_instance();
  
  void Swap(BattleStartRequest* other);
  
  // implements Message ----------------------------------------------
  
  BattleStartRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BattleStartRequest& from);
  void MergeFrom(const BattleStartRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string mailAddress = 1;
  inline bool has_mailaddress() const;
  inline void clear_mailaddress();
  static const int kMailAddressFieldNumber = 1;
  inline const ::std::string& mailaddress() const;
  inline void set_mailaddress(const ::std::string& value);
  inline void set_mailaddress(const char* value);
  inline void set_mailaddress(const char* value, size_t size);
  inline ::std::string* mutable_mailaddress();
  inline ::std::string* release_mailaddress();
  
  // required string defenceMailAddress = 2;
  inline bool has_defencemailaddress() const;
  inline void clear_defencemailaddress();
  static const int kDefenceMailAddressFieldNumber = 2;
  inline const ::std::string& defencemailaddress() const;
  inline void set_defencemailaddress(const ::std::string& value);
  inline void set_defencemailaddress(const char* value);
  inline void set_defencemailaddress(const char* value, size_t size);
  inline ::std::string* mutable_defencemailaddress();
  inline ::std::string* release_defencemailaddress();
  
  // required string start_battle_time = 3;
  inline bool has_start_battle_time() const;
  inline void clear_start_battle_time();
  static const int kStartBattleTimeFieldNumber = 3;
  inline const ::std::string& start_battle_time() const;
  inline void set_start_battle_time(const ::std::string& value);
  inline void set_start_battle_time(const char* value);
  inline void set_start_battle_time(const char* value, size_t size);
  inline ::std::string* mutable_start_battle_time();
  inline ::std::string* release_start_battle_time();
  
  // @@protoc_insertion_point(class_scope:message.BattleStartRequest)
 private:
  inline void set_has_mailaddress();
  inline void clear_has_mailaddress();
  inline void set_has_defencemailaddress();
  inline void clear_has_defencemailaddress();
  inline void set_has_start_battle_time();
  inline void clear_has_start_battle_time();
  
  ::std::string* mailaddress_;
  ::std::string* defencemailaddress_;
  ::std::string* start_battle_time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_BattleStart_2eproto();
  friend void protobuf_AssignDesc_BattleStart_2eproto();
  friend void protobuf_ShutdownFile_BattleStart_2eproto();
  
  void InitAsDefaultInstance();
  static BattleStartRequest* default_instance_;
};
// -------------------------------------------------------------------

class BattleStartResponse : public ::google::protobuf::MessageLite {
 public:
  BattleStartResponse();
  virtual ~BattleStartResponse();
  
  BattleStartResponse(const BattleStartResponse& from);
  
  inline BattleStartResponse& operator=(const BattleStartResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BattleStartResponse& default_instance();
  
  void Swap(BattleStartResponse* other);
  
  // implements Message ----------------------------------------------
  
  BattleStartResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BattleStartResponse& from);
  void MergeFrom(const BattleStartResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional sint32 result = 1 [default = 0];
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // optional string info = 2;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 2;
  inline const ::std::string& info() const;
  inline void set_info(const ::std::string& value);
  inline void set_info(const char* value);
  inline void set_info(const char* value, size_t size);
  inline ::std::string* mutable_info();
  inline ::std::string* release_info();
  
  // optional int64 battleId = 3;
  inline bool has_battleid() const;
  inline void clear_battleid();
  static const int kBattleIdFieldNumber = 3;
  inline ::google::protobuf::int64 battleid() const;
  inline void set_battleid(::google::protobuf::int64 value);
  
  // optional uint64 verifyCode = 4;
  inline bool has_verifycode() const;
  inline void clear_verifycode();
  static const int kVerifyCodeFieldNumber = 4;
  inline ::google::protobuf::uint64 verifycode() const;
  inline void set_verifycode(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:message.BattleStartResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_info();
  inline void clear_has_info();
  inline void set_has_battleid();
  inline void clear_has_battleid();
  inline void set_has_verifycode();
  inline void clear_has_verifycode();
  
  ::std::string* info_;
  ::google::protobuf::int64 battleid_;
  ::google::protobuf::uint64 verifycode_;
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_BattleStart_2eproto();
  friend void protobuf_AssignDesc_BattleStart_2eproto();
  friend void protobuf_ShutdownFile_BattleStart_2eproto();
  
  void InitAsDefaultInstance();
  static BattleStartResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BattleStartRequest

// required string mailAddress = 1;
inline bool BattleStartRequest::has_mailaddress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BattleStartRequest::set_has_mailaddress() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BattleStartRequest::clear_has_mailaddress() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BattleStartRequest::clear_mailaddress() {
  if (mailaddress_ != &::google::protobuf::internal::kEmptyString) {
    mailaddress_->clear();
  }
  clear_has_mailaddress();
}
inline const ::std::string& BattleStartRequest::mailaddress() const {
  return *mailaddress_;
}
inline void BattleStartRequest::set_mailaddress(const ::std::string& value) {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  mailaddress_->assign(value);
}
inline void BattleStartRequest::set_mailaddress(const char* value) {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  mailaddress_->assign(value);
}
inline void BattleStartRequest::set_mailaddress(const char* value, size_t size) {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  mailaddress_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BattleStartRequest::mutable_mailaddress() {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  return mailaddress_;
}
inline ::std::string* BattleStartRequest::release_mailaddress() {
  clear_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mailaddress_;
    mailaddress_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string defenceMailAddress = 2;
inline bool BattleStartRequest::has_defencemailaddress() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BattleStartRequest::set_has_defencemailaddress() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BattleStartRequest::clear_has_defencemailaddress() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BattleStartRequest::clear_defencemailaddress() {
  if (defencemailaddress_ != &::google::protobuf::internal::kEmptyString) {
    defencemailaddress_->clear();
  }
  clear_has_defencemailaddress();
}
inline const ::std::string& BattleStartRequest::defencemailaddress() const {
  return *defencemailaddress_;
}
inline void BattleStartRequest::set_defencemailaddress(const ::std::string& value) {
  set_has_defencemailaddress();
  if (defencemailaddress_ == &::google::protobuf::internal::kEmptyString) {
    defencemailaddress_ = new ::std::string;
  }
  defencemailaddress_->assign(value);
}
inline void BattleStartRequest::set_defencemailaddress(const char* value) {
  set_has_defencemailaddress();
  if (defencemailaddress_ == &::google::protobuf::internal::kEmptyString) {
    defencemailaddress_ = new ::std::string;
  }
  defencemailaddress_->assign(value);
}
inline void BattleStartRequest::set_defencemailaddress(const char* value, size_t size) {
  set_has_defencemailaddress();
  if (defencemailaddress_ == &::google::protobuf::internal::kEmptyString) {
    defencemailaddress_ = new ::std::string;
  }
  defencemailaddress_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BattleStartRequest::mutable_defencemailaddress() {
  set_has_defencemailaddress();
  if (defencemailaddress_ == &::google::protobuf::internal::kEmptyString) {
    defencemailaddress_ = new ::std::string;
  }
  return defencemailaddress_;
}
inline ::std::string* BattleStartRequest::release_defencemailaddress() {
  clear_has_defencemailaddress();
  if (defencemailaddress_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = defencemailaddress_;
    defencemailaddress_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string start_battle_time = 3;
inline bool BattleStartRequest::has_start_battle_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BattleStartRequest::set_has_start_battle_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BattleStartRequest::clear_has_start_battle_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BattleStartRequest::clear_start_battle_time() {
  if (start_battle_time_ != &::google::protobuf::internal::kEmptyString) {
    start_battle_time_->clear();
  }
  clear_has_start_battle_time();
}
inline const ::std::string& BattleStartRequest::start_battle_time() const {
  return *start_battle_time_;
}
inline void BattleStartRequest::set_start_battle_time(const ::std::string& value) {
  set_has_start_battle_time();
  if (start_battle_time_ == &::google::protobuf::internal::kEmptyString) {
    start_battle_time_ = new ::std::string;
  }
  start_battle_time_->assign(value);
}
inline void BattleStartRequest::set_start_battle_time(const char* value) {
  set_has_start_battle_time();
  if (start_battle_time_ == &::google::protobuf::internal::kEmptyString) {
    start_battle_time_ = new ::std::string;
  }
  start_battle_time_->assign(value);
}
inline void BattleStartRequest::set_start_battle_time(const char* value, size_t size) {
  set_has_start_battle_time();
  if (start_battle_time_ == &::google::protobuf::internal::kEmptyString) {
    start_battle_time_ = new ::std::string;
  }
  start_battle_time_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BattleStartRequest::mutable_start_battle_time() {
  set_has_start_battle_time();
  if (start_battle_time_ == &::google::protobuf::internal::kEmptyString) {
    start_battle_time_ = new ::std::string;
  }
  return start_battle_time_;
}
inline ::std::string* BattleStartRequest::release_start_battle_time() {
  clear_has_start_battle_time();
  if (start_battle_time_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = start_battle_time_;
    start_battle_time_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// BattleStartResponse

// optional sint32 result = 1 [default = 0];
inline bool BattleStartResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BattleStartResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BattleStartResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BattleStartResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 BattleStartResponse::result() const {
  return result_;
}
inline void BattleStartResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional string info = 2;
inline bool BattleStartResponse::has_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BattleStartResponse::set_has_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BattleStartResponse::clear_has_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BattleStartResponse::clear_info() {
  if (info_ != &::google::protobuf::internal::kEmptyString) {
    info_->clear();
  }
  clear_has_info();
}
inline const ::std::string& BattleStartResponse::info() const {
  return *info_;
}
inline void BattleStartResponse::set_info(const ::std::string& value) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  info_->assign(value);
}
inline void BattleStartResponse::set_info(const char* value) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  info_->assign(value);
}
inline void BattleStartResponse::set_info(const char* value, size_t size) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  info_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BattleStartResponse::mutable_info() {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  return info_;
}
inline ::std::string* BattleStartResponse::release_info() {
  clear_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = info_;
    info_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int64 battleId = 3;
inline bool BattleStartResponse::has_battleid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BattleStartResponse::set_has_battleid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BattleStartResponse::clear_has_battleid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BattleStartResponse::clear_battleid() {
  battleid_ = GOOGLE_LONGLONG(0);
  clear_has_battleid();
}
inline ::google::protobuf::int64 BattleStartResponse::battleid() const {
  return battleid_;
}
inline void BattleStartResponse::set_battleid(::google::protobuf::int64 value) {
  set_has_battleid();
  battleid_ = value;
}

// optional uint64 verifyCode = 4;
inline bool BattleStartResponse::has_verifycode() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BattleStartResponse::set_has_verifycode() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BattleStartResponse::clear_has_verifycode() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BattleStartResponse::clear_verifycode() {
  verifycode_ = GOOGLE_ULONGLONG(0);
  clear_has_verifycode();
}
inline ::google::protobuf::uint64 BattleStartResponse::verifycode() const {
  return verifycode_;
}
inline void BattleStartResponse::set_verifycode(::google::protobuf::uint64 value) {
  set_has_verifycode();
  verifycode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleStart_2eproto__INCLUDED
