// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProduceSoldiers.proto

#ifndef PROTOBUF_ProduceSoldiers_2eproto__INCLUDED
#define PROTOBUF_ProduceSoldiers_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProduceSoldiers_2eproto();
void protobuf_AssignDesc_ProduceSoldiers_2eproto();
void protobuf_ShutdownFile_ProduceSoldiers_2eproto();

class ProduceSoldiersRequest;
class ProduceSoldiersRequest_ProduceSoldiers;
class ProduceSoldiersResponse;

// ===================================================================

class ProduceSoldiersRequest_ProduceSoldiers : public ::google::protobuf::MessageLite {
 public:
  ProduceSoldiersRequest_ProduceSoldiers();
  virtual ~ProduceSoldiersRequest_ProduceSoldiers();
  
  ProduceSoldiersRequest_ProduceSoldiers(const ProduceSoldiersRequest_ProduceSoldiers& from);
  
  inline ProduceSoldiersRequest_ProduceSoldiers& operator=(const ProduceSoldiersRequest_ProduceSoldiers& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const ProduceSoldiersRequest_ProduceSoldiers& default_instance();
  
  void Swap(ProduceSoldiersRequest_ProduceSoldiers* other);
  
  // implements Message ----------------------------------------------
  
  ProduceSoldiersRequest_ProduceSoldiers* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ProduceSoldiersRequest_ProduceSoldiers& from);
  void MergeFrom(const ProduceSoldiersRequest_ProduceSoldiers& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 character_id = 1;
  inline bool has_character_id() const;
  inline void clear_character_id();
  static const int kCharacterIdFieldNumber = 1;
  inline ::google::protobuf::int32 character_id() const;
  inline void set_character_id(::google::protobuf::int32 value);
  
  // optional int32 character_level = 2;
  inline bool has_character_level() const;
  inline void clear_character_level();
  static const int kCharacterLevelFieldNumber = 2;
  inline ::google::protobuf::int32 character_level() const;
  inline void set_character_level(::google::protobuf::int32 value);
  
  // optional int32 produce_count = 3;
  inline bool has_produce_count() const;
  inline void clear_produce_count();
  static const int kProduceCountFieldNumber = 3;
  inline ::google::protobuf::int32 produce_count() const;
  inline void set_produce_count(::google::protobuf::int32 value);
  
  // optional int32 index = 4;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 4;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);
  
  // optional int32 uuid = 5;
  inline bool has_uuid() const;
  inline void clear_uuid();
  static const int kUuidFieldNumber = 5;
  inline ::google::protobuf::int32 uuid() const;
  inline void set_uuid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:message.ProduceSoldiersRequest.ProduceSoldiers)
 private:
  inline void set_has_character_id();
  inline void clear_has_character_id();
  inline void set_has_character_level();
  inline void clear_has_character_level();
  inline void set_has_produce_count();
  inline void clear_has_produce_count();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_uuid();
  inline void clear_has_uuid();
  
  ::google::protobuf::int32 character_id_;
  ::google::protobuf::int32 character_level_;
  ::google::protobuf::int32 produce_count_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 uuid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProduceSoldiers_2eproto();
  friend void protobuf_AssignDesc_ProduceSoldiers_2eproto();
  friend void protobuf_ShutdownFile_ProduceSoldiers_2eproto();
  
  void InitAsDefaultInstance();
  static ProduceSoldiersRequest_ProduceSoldiers* default_instance_;
};
// -------------------------------------------------------------------

class ProduceSoldiersRequest : public ::google::protobuf::MessageLite {
 public:
  ProduceSoldiersRequest();
  virtual ~ProduceSoldiersRequest();
  
  ProduceSoldiersRequest(const ProduceSoldiersRequest& from);
  
  inline ProduceSoldiersRequest& operator=(const ProduceSoldiersRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const ProduceSoldiersRequest& default_instance();
  
  void Swap(ProduceSoldiersRequest* other);
  
  // implements Message ----------------------------------------------
  
  ProduceSoldiersRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ProduceSoldiersRequest& from);
  void MergeFrom(const ProduceSoldiersRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  typedef ProduceSoldiersRequest_ProduceSoldiers ProduceSoldiers;
  
  // accessors -------------------------------------------------------
  
  // required string mailAddress = 1;
  inline bool has_mailaddress() const;
  inline void clear_mailaddress();
  static const int kMailAddressFieldNumber = 1;
  inline const ::std::string& mailaddress() const;
  inline void set_mailaddress(const ::std::string& value);
  inline void set_mailaddress(const char* value);
  inline void set_mailaddress(const char* value, size_t size);
  inline ::std::string* mutable_mailaddress();
  inline ::std::string* release_mailaddress();
  
  // repeated .message.ProduceSoldiersRequest.ProduceSoldiers soldiersList = 2;
  inline int soldierslist_size() const;
  inline void clear_soldierslist();
  static const int kSoldiersListFieldNumber = 2;
  inline const ::message::ProduceSoldiersRequest_ProduceSoldiers& soldierslist(int index) const;
  inline ::message::ProduceSoldiersRequest_ProduceSoldiers* mutable_soldierslist(int index);
  inline ::message::ProduceSoldiersRequest_ProduceSoldiers* add_soldierslist();
  inline const ::google::protobuf::RepeatedPtrField< ::message::ProduceSoldiersRequest_ProduceSoldiers >&
      soldierslist() const;
  inline ::google::protobuf::RepeatedPtrField< ::message::ProduceSoldiersRequest_ProduceSoldiers >*
      mutable_soldierslist();
  
  // optional int32 create_state = 3;
  inline bool has_create_state() const;
  inline void clear_create_state();
  static const int kCreateStateFieldNumber = 3;
  inline ::google::protobuf::int32 create_state() const;
  inline void set_create_state(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:message.ProduceSoldiersRequest)
 private:
  inline void set_has_mailaddress();
  inline void clear_has_mailaddress();
  inline void set_has_create_state();
  inline void clear_has_create_state();
  
  ::std::string* mailaddress_;
  ::google::protobuf::RepeatedPtrField< ::message::ProduceSoldiersRequest_ProduceSoldiers > soldierslist_;
  ::google::protobuf::int32 create_state_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProduceSoldiers_2eproto();
  friend void protobuf_AssignDesc_ProduceSoldiers_2eproto();
  friend void protobuf_ShutdownFile_ProduceSoldiers_2eproto();
  
  void InitAsDefaultInstance();
  static ProduceSoldiersRequest* default_instance_;
};
// -------------------------------------------------------------------

class ProduceSoldiersResponse : public ::google::protobuf::MessageLite {
 public:
  ProduceSoldiersResponse();
  virtual ~ProduceSoldiersResponse();
  
  ProduceSoldiersResponse(const ProduceSoldiersResponse& from);
  
  inline ProduceSoldiersResponse& operator=(const ProduceSoldiersResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const ProduceSoldiersResponse& default_instance();
  
  void Swap(ProduceSoldiersResponse* other);
  
  // implements Message ----------------------------------------------
  
  ProduceSoldiersResponse* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ProduceSoldiersResponse& from);
  void MergeFrom(const ProduceSoldiersResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional sint32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);
  
  // optional string info = 2;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 2;
  inline const ::std::string& info() const;
  inline void set_info(const ::std::string& value);
  inline void set_info(const char* value);
  inline void set_info(const char* value, size_t size);
  inline ::std::string* mutable_info();
  inline ::std::string* release_info();
  
  // @@protoc_insertion_point(class_scope:message.ProduceSoldiersResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_info();
  inline void clear_has_info();
  
  ::std::string* info_;
  ::google::protobuf::int32 result_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProduceSoldiers_2eproto();
  friend void protobuf_AssignDesc_ProduceSoldiers_2eproto();
  friend void protobuf_ShutdownFile_ProduceSoldiers_2eproto();
  
  void InitAsDefaultInstance();
  static ProduceSoldiersResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// ProduceSoldiersRequest_ProduceSoldiers

// optional int32 character_id = 1;
inline bool ProduceSoldiersRequest_ProduceSoldiers::has_character_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_has_character_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_has_character_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_character_id() {
  character_id_ = 0;
  clear_has_character_id();
}
inline ::google::protobuf::int32 ProduceSoldiersRequest_ProduceSoldiers::character_id() const {
  return character_id_;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_character_id(::google::protobuf::int32 value) {
  set_has_character_id();
  character_id_ = value;
}

// optional int32 character_level = 2;
inline bool ProduceSoldiersRequest_ProduceSoldiers::has_character_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_has_character_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_has_character_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_character_level() {
  character_level_ = 0;
  clear_has_character_level();
}
inline ::google::protobuf::int32 ProduceSoldiersRequest_ProduceSoldiers::character_level() const {
  return character_level_;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_character_level(::google::protobuf::int32 value) {
  set_has_character_level();
  character_level_ = value;
}

// optional int32 produce_count = 3;
inline bool ProduceSoldiersRequest_ProduceSoldiers::has_produce_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_has_produce_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_has_produce_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_produce_count() {
  produce_count_ = 0;
  clear_has_produce_count();
}
inline ::google::protobuf::int32 ProduceSoldiersRequest_ProduceSoldiers::produce_count() const {
  return produce_count_;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_produce_count(::google::protobuf::int32 value) {
  set_has_produce_count();
  produce_count_ = value;
}

// optional int32 index = 4;
inline bool ProduceSoldiersRequest_ProduceSoldiers::has_index() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_has_index() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_has_index() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 ProduceSoldiersRequest_ProduceSoldiers::index() const {
  return index_;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
}

// optional int32 uuid = 5;
inline bool ProduceSoldiersRequest_ProduceSoldiers::has_uuid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_has_uuid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::clear_uuid() {
  uuid_ = 0;
  clear_has_uuid();
}
inline ::google::protobuf::int32 ProduceSoldiersRequest_ProduceSoldiers::uuid() const {
  return uuid_;
}
inline void ProduceSoldiersRequest_ProduceSoldiers::set_uuid(::google::protobuf::int32 value) {
  set_has_uuid();
  uuid_ = value;
}

// -------------------------------------------------------------------

// ProduceSoldiersRequest

// required string mailAddress = 1;
inline bool ProduceSoldiersRequest::has_mailaddress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProduceSoldiersRequest::set_has_mailaddress() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProduceSoldiersRequest::clear_has_mailaddress() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProduceSoldiersRequest::clear_mailaddress() {
  if (mailaddress_ != &::google::protobuf::internal::kEmptyString) {
    mailaddress_->clear();
  }
  clear_has_mailaddress();
}
inline const ::std::string& ProduceSoldiersRequest::mailaddress() const {
  return *mailaddress_;
}
inline void ProduceSoldiersRequest::set_mailaddress(const ::std::string& value) {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  mailaddress_->assign(value);
}
inline void ProduceSoldiersRequest::set_mailaddress(const char* value) {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  mailaddress_->assign(value);
}
inline void ProduceSoldiersRequest::set_mailaddress(const char* value, size_t size) {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  mailaddress_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ProduceSoldiersRequest::mutable_mailaddress() {
  set_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    mailaddress_ = new ::std::string;
  }
  return mailaddress_;
}
inline ::std::string* ProduceSoldiersRequest::release_mailaddress() {
  clear_has_mailaddress();
  if (mailaddress_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mailaddress_;
    mailaddress_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .message.ProduceSoldiersRequest.ProduceSoldiers soldiersList = 2;
inline int ProduceSoldiersRequest::soldierslist_size() const {
  return soldierslist_.size();
}
inline void ProduceSoldiersRequest::clear_soldierslist() {
  soldierslist_.Clear();
}
inline const ::message::ProduceSoldiersRequest_ProduceSoldiers& ProduceSoldiersRequest::soldierslist(int index) const {
  return soldierslist_.Get(index);
}
inline ::message::ProduceSoldiersRequest_ProduceSoldiers* ProduceSoldiersRequest::mutable_soldierslist(int index) {
  return soldierslist_.Mutable(index);
}
inline ::message::ProduceSoldiersRequest_ProduceSoldiers* ProduceSoldiersRequest::add_soldierslist() {
  return soldierslist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::ProduceSoldiersRequest_ProduceSoldiers >&
ProduceSoldiersRequest::soldierslist() const {
  return soldierslist_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::ProduceSoldiersRequest_ProduceSoldiers >*
ProduceSoldiersRequest::mutable_soldierslist() {
  return &soldierslist_;
}

// optional int32 create_state = 3;
inline bool ProduceSoldiersRequest::has_create_state() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProduceSoldiersRequest::set_has_create_state() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProduceSoldiersRequest::clear_has_create_state() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProduceSoldiersRequest::clear_create_state() {
  create_state_ = 0;
  clear_has_create_state();
}
inline ::google::protobuf::int32 ProduceSoldiersRequest::create_state() const {
  return create_state_;
}
inline void ProduceSoldiersRequest::set_create_state(::google::protobuf::int32 value) {
  set_has_create_state();
  create_state_ = value;
}

// -------------------------------------------------------------------

// ProduceSoldiersResponse

// optional sint32 result = 1;
inline bool ProduceSoldiersResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProduceSoldiersResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProduceSoldiersResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProduceSoldiersResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 ProduceSoldiersResponse::result() const {
  return result_;
}
inline void ProduceSoldiersResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional string info = 2;
inline bool ProduceSoldiersResponse::has_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProduceSoldiersResponse::set_has_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProduceSoldiersResponse::clear_has_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProduceSoldiersResponse::clear_info() {
  if (info_ != &::google::protobuf::internal::kEmptyString) {
    info_->clear();
  }
  clear_has_info();
}
inline const ::std::string& ProduceSoldiersResponse::info() const {
  return *info_;
}
inline void ProduceSoldiersResponse::set_info(const ::std::string& value) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  info_->assign(value);
}
inline void ProduceSoldiersResponse::set_info(const char* value) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  info_->assign(value);
}
inline void ProduceSoldiersResponse::set_info(const char* value, size_t size) {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  info_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ProduceSoldiersResponse::mutable_info() {
  set_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    info_ = new ::std::string;
  }
  return info_;
}
inline ::std::string* ProduceSoldiersResponse::release_info() {
  clear_has_info();
  if (info_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = info_;
    info_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProduceSoldiers_2eproto__INCLUDED
